version: '3'

services:
  phpfpm:
    build: ./php
    container_name: doc-phpfpm
    volumes:
      - ./application:/var/www
    depends_on:
      # - redis
      - db

  nginx:
    restart: always
    image: nginx:1.17-alpine
    container_name: doc-nginx
    ports:
      - 8080:80
    volumes:
      - ./application:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - redis
      - db
      - phpfpm

  db:
    restart: always
    image: mysql:5.7
    container_name: doc-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/mysql_conf/:/etc/mysql/conf.d
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  # redis:
  #   restart: always
  #   image: redis:5.0
  #   container_name: doc-redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis/data:/data
  #   command: redis-server --appendonly yes

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   container_name: doc-phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=db
  #     - PMA_USER=root
  #     - PMA_PASSWORD=pass
  #   depends_on:
  #     - db
  #   ports:
  #     - 8888:80
  #   volumes:
  #     - ./phpmyadmin/sessions:/sessions