name: PHP Coding Standards Fixer

on:
  pull_request:
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dokcer-compose up
        run: docker-compose build && docker-compose up -d
      
      - name: composer update
        run: docker-compose exec -T phpfpm bash -c "composer update"
      
      - name: composer install
        run: docker-compose exec -T phpfpm bash -c "composer install"

      - name: OS Version
        run: cat /etc/os-release

      - name: PHP Version
        run: php -v

      - name: PHP CS Fixer Version
        run: php php-cs-fixer --version

      - name: PHP CS Fixer Dry Run
        run: docker-compose exec -T phpfpm bash -c "./vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no ."

      - name: PHP CS Fixer Execute
        run: docker-compose exec -T phpfpm bash -c "./vendor/bin/php-cs-fixer fix --using-cache=no ."